server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: version1
          uri: lb://version-1
          predicates:
            - Path=/v1.0/{segment}
        - id: version2
          uri: lb://version-1.1
          predicates:
            - Path=/v1.1/{segment}
        - id: version3
          uri: lb://version-1.2
          predicates:
            - Path=/v1.2/{segment}