server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    appname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: version1
          uri: lb://VERSION-ONE/
          predicates:
            - Path=/v1.0/*
        - id: version2
          uri: lb://version-two
          predicates:
            - Path=/v1.1/*
        - id: version3
          uri: lb://version-three
          predicates:
            - Path=/v1.2/*
logging:
  level:
    org.springframework:
      cloud.gateway: DEBUG
      web: DEBUG
      http: DEBUG
